name: "Jest GitHub Action"
description: "Jest action adding checks and annotations to your pull requests and comment them with code coverage results."
branding:
  icon: "check"
  color: "green"
inputs:
  test-command:
    description: "The test command to run"
    required: false
    default: "npm test"
  working-directory:
    description: "Subdirectory to run tests in"
    required: false
    default: ""
  coverage-comment:
    description: "Comment PRs with code coverage"
    required: false
    default: "true"
  github-token:
    description: "Github token for running the action"
    required: true

runs:
  using: "node16"
  main: "dist/index.js"
