name: "Jest GitHub Action"
description: "Jest action adding checks and annotations to your pull requests and comment them with code coverage results."
branding:
  icon: "check"
  color: "green"
inputs:
  report-file:
    description: "Report file that should be shown"
    required: true
    default: "report.json"
  github-token:
    description: "Github token for running the action"
    required: true
  working-directory:
    description: "Subdirectory to run tests in"
    required: false
    default: ""
  coverage-comment:
    description: "Comment PRs with code coverage"
    required: false
    default: "true"


runs:
  using: "node16"
  main: "dist/index.js"
